[package]
name = "darknet"
version = "0.1.3"
authors = ["alianse77"]
edition = "2018"
description = "A Rust wrapper for Darknet, an open source neural network framework written in C and CUDA."
repository = "https://github.com/alianse777/darknet-rust"
license = "MIT"
keywords = ["darknet", "machine-learning", "deep-learning", "neural-networks", "yolo"]
readme = "./README.md"

[dependencies]
darknet-sys = { version = "^0.2.0", path = "/mnt/ssd2/home/aeon/repo/darknet-sys-rust" }
image = "^0.23.1"
libc = "^0.2.0"
failure = "^0.1.8"
num-derive = "^0.3.0"
num-traits = "^0.2.0"

[dev-dependencies]
itertools = "^0.9.0"